urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('',
    (r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'wall.views.Wall'),
    url(r'^logout', 'profiles.views.User_Profile_Logout'),
    url(r'^register$', 'profiles.views.User_Profile_Registration'),
    url(r'^registered$', 'profiles.views.User_Profile_Registration_Finished'),
    url(r'^login', 'profiles.views.User_Profile_Login'),
    url(r'^search/', 'profiles.views.User_Profile_Search'),
    url(r'^edit/$', 'profiles.views.User_Profile_Edit'),
    url(r'^friends/(?P<username>[\w]+)', 'profiles.views.User_Profile_Friends', name="friendlist"),
    url(r'^json/(?P<search_keyword>[\w ]+)', 'profiles.views.json_searching'),


    url(r'^profile/(?P<username>[\w]+)/add', 'profiles.views.Specific_User_Profile_Add', name="specific_add"),
    url(r'^profile/(?P<username>[\w]+)/remove', 'profiles.views.Specific_User_Profile_Remove', name="specific_remove"),
    url(r'^profile/(?P<username>[\w]+)', 'profiles.views.Specific_User_Profile_Show', name="specific_url"),
    url(r'^profile/$', 'profiles.views.User_Profile_Show'),


    url(r'^chat/(?P<username>[\w]+)/json/last/seen', 'messages.views.Chat_Last_Seen'),
    url(r'^chat/(?P<username>[\w]+)/json/last', 'messages.views.Chat_Last_Item_PK'),
    url(r'^chat/(?P<username>[\w]+)/json/seen', 'messages.views.Chat_Seen'),
    url(r'^chat/(?P<username>[\w]+)/json/(?P<message_id>[0-9]+)', 'messages.views.Chat_Specific_Message'),
    url(r'^chat/(?P<username>[\w]+)/json', 'messages.views.Chat_With_JSON'),
    url(r'^chat/(?P<username>[\w]+)', 'messages.views.Chat_With'),


    url(r'^wallpost/addPost$', 'wall.views.addWallPost', name="addWallPost"),
    url(r'^wallpost/addComment/(?P<PostID>[0-9]+)', 'wall.views.addWallComment', name="addWallComment"),
    url(r'^wallpost/deleteComment/(?P<PostID>[0-9]+)', 'wall.views.removeWallComment', name="deleteComment"),
    url(r'^wallpost/(?P<PostID>[0-9]+)/comments', 'wall.views.WallPostComments', name="ListComments"),
    url(r'^wallpost/(?P<pk>[0-9]+)/like$', 'wall.views.LikeWallPost', name="LikeWallPost"),
    url(r'^wallpost/(?P<pk>[0-9]+)/dislike$', 'wall.views.DislikeWallPost', name="DislikeWallPost"),
    url(r'^wallpost/(?P<pk>[0-9]+)$', 'wall.views.singlePost', name="specific_post"),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)
urlpatterns += staticfiles_urlpatterns()

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

profiles/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from countries.models import *
from django.utils.translation import ugettext_lazy as _

class Profile(models.Model):
    birth_date   = models.DateField(_('Birthday'), null=True, blank=True)
    countries    = models.ForeignKey(Country, null=True, blank=True)
    user         = models.OneToOneField(User)
    profile_pic  = models.ImageField(upload_to='tmp/', null=True, blank=True)
    friends      = models.ManyToManyField(User, null=True, blank=True, related_name='uf+')
    about_me     = models.TextField(_('About Me'), null=True, blank=True)

    def __unicode__(self):
        return self.user.get_full_name()

admin.site.register(Profile)

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from profiles.models import Profile

class RegistrationForm(ModelForm):
    first_name  = forms.CharField(label=(u'First Name'))
    last_name   = forms.CharField(label=(u'Last Name'))
    username    = forms.CharField(label=(u'User Name'))
    email       = forms.EmailField(label=(u'Email'))
    password    = forms.CharField(label=(u'Password'), widget=forms.PasswordInput(render_value=False))
    password1   = forms.CharField(label=(u'Verify Password'), widget=forms.PasswordInput(render_value=False))

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = [
                                'first_name',
                                'last_name',
                                'birth_date',
                                'countries',
                                'username',
                                'email',
                                'password',
                                'password1',
                                'profile_pic',
                                'about_me',
                                ]

    class Meta:
        model = Profile
        exclude = ('user','friends')

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError('That username is taken.')

    def clean(self):
        if self.cleaned_data['password'] != self.cleaned_data['password1']:
            raise forms.ValidationError('The passwords does not match!')
        return self.cleaned_data

class LoginForm(forms.Form):
    username        = forms.CharField(label=(u'Username'), widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password        = forms.CharField(label=(u'Password'), widget=forms.PasswordInput(render_value=False,attrs={'placeholder': 'Password'}))

class EditForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ('user','friends')


profiles/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from profiles.forms import *
from profiles.models import Profile
from django.contrib.auth import logout
from datetime import date
from django.utils import simplejson
from fuzzywuzzy import fuzz

def User_Profile_Registration(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['profile_pic'])
            user = User.objects.create_user(username=form.cleaned_data['username'], email = form.cleaned_data['email'], password = form.cleaned_data['password'])
            user.first_name = form.cleaned_data['first_name']
            user.last_name=form.cleaned_data['last_name']
            user.save()
            profile = Profile(user = user, countries=form.cleaned_data['countries'], about_me = form.cleaned_data['about_me'], birth_date = form.cleaned_data['birth_date'])
            profile.profile_pic=form.cleaned_data['profile_pic']
            profile.save()
            registredUser = authenticate(username = form.cleaned_data['username'], password= form.cleaned_data['password'])
            if registredUser is not None:
                login(request, registredUser)
                return HttpResponseRedirect('/')

            else:
                return HttpResponseRedirect('/registered')
    else:
        form = RegistrationForm()
        context = { 'form' : form }
        return render_to_response('register.html', context, context_instance=RequestContext(request))
    return HttpResponseRedirect('/')

def User_Profile_Registration_Finished(request):
    return render_to_response('registered.html', context_instance=RequestContext(request))

def User_Profile_Login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        print form
        if form.is_valid():
            myProfile = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if myProfile is not None:
                login(request, myProfile)
                return HttpResponseRedirect('/')
            else:
                return render_to_response('login.html', { 'form': form }, context_instance=RequestContext(request))
        else:
            return render_to_response('login.html', { 'form': form }, context_instance=RequestContext(request))
    else:
        form = LoginForm()
        context = { 'form' : form }
        return render_to_response('login.html', context, context_instance=RequestContext(request))

@login_required
def User_Profile_Show(request):
    user = request.user
    age = calculate_age(user.get_profile().birth_date)
    context = {
                'profiles' : user,
                'age':age,
                'friendable': "none",
              }
    return render_to_response('profile.html', context, context_instance=RequestContext(request))

def Specific_User_Profile_Show(request,username):
    user = User.objects.get(username=username)
    age = calculate_age(user.get_profile().birth_date)
    context = {
                'profiles' : user,
                'age':age,
                'friendable': "none",
    }
    if not username == request.user.username:
        context['friendable']=Profile.objects.filter(user=request.user,friends=user).count

    return render_to_response('profile.html', context, context_instance=RequestContext(request))

@login_required
def User_Profile_Logout(request):
    logout(request)
    return HttpResponseRedirect('/')

def User_Profile_Search(request):
    if request.method == 'POST':
        search_keyword = request.POST['search_keyword']
        users = User.objects.filter(Q(username__icontains=search_keyword) | Q(first_name__icontains=search_keyword) | Q(last_name__icontains=search_keyword))
        context = {
            'search_results' : users
        }
        return render_to_response('search.html', context, context_instance=RequestContext(request))

@login_required
def Specific_User_Profile_Add(request,username):
    user  = User.objects.get(username=username)
    request.user.get_profile().friends.add(user)
    return HttpResponseRedirect('/profile/'+username)

@login_required
def Specific_User_Profile_Remove(request,username):
    user  = User.objects.get(username=username)
    request.user.get_profile().friends.remove(user)
    return HttpResponseRedirect('/profile/'+username)

def json_searching(request,search_keyword):
    #check if it contains space if it does, then it must be a name
    #or partial name, else it can be a nickname too
    if (' ' in search_keyword) == True:
        search_keywords = search_keyword.split(' ')
        first  = ''.join(search_keywords[0])
        second = ''.join(search_keywords[1])
        users = User.objects.filter(( Q(first_name__icontains=first) & Q(last_name__icontains=second) )
                                  | (Q(first_name__icontains=second) & Q(last_name__icontains=first)))
    else:
        users = User.objects.filter(Q(username__icontains=search_keyword)
                                  | Q(first_name__icontains=search_keyword)
                                  | Q(last_name__icontains=search_keyword))
    response_data=[]
    for user in users:
        #check query similarities
        if fuzz.token_sort_ratio(user.get_full_name(), search_keyword) > fuzz.ratio(user.username, search_keyword):
            similarity=fuzz.token_sort_ratio(user.get_full_name(), search_keyword)
        else:
            similarity=fuzz.ratio(user.username, search_keyword)

        #bonus for living in the same area (country)
        if request.user.get_profile().countries == user.get_profile().countries:
            similarity += 10
        #remove 50 points for being yourself and if match is only partial found.
        if request.user == user and not ( user.get_full_name().lower() ==  search_keyword.lower()
                                       or user.username.lower() == search_keyword.lower()
                                       or user.last_name.lower()+' '+user.first_name.lower() == search_keyword.lower() ):
            similarity -= 50

        response_data +=[
             (user.username,
             user.get_full_name(),
             user.get_profile().profile_pic.url,
             similarity)
        ]
    #sort by similarity
    sorted_data=sorted(response_data, key=lambda a:a[3], reverse=True)
    return HttpResponse(simplejson.dumps(sorted_data[:10]), mimetype="application/json")

@login_required
def User_Profile_Edit(request):
    #TODO: ability to edit your profile.
    if request.method == 'POST':
        form = EditForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['profile_pic'])
            member = request.user.profile
            member.birth_date   = form.cleaned_data['birth_date']
            member.countries    = form.cleaned_data['countries']
            member.about_me     = form.cleaned_data['about_me']
            member.profile_pic  = form.cleaned_data['profile_pic']
            member.save();
        return render_to_response('edit.html', {}, context_instance=RequestContext(request))
    else:
        member = request.user.get_profile()
        data = {
            'birth_date': member.birth_date,
            'profile_pic': member.profile_pic,
            'countries': member.countries,
            'about_me': member.about_me
        }
        form = EditForm(initial=data)
        context= {
            'form': form
        }
        return render_to_response('edit.html', context, context_instance=RequestContext(request))

@login_required
def User_Profile_Friends(request, username=""):
    member = User.objects.get(username = username)
    friends = member.get_profile().friends

    context= {
        'friends': friends,
        'member': member,
    }
    return render_to_response('friends.html', context, context_instance=RequestContext(request))

def error_404(request):
    return render_to_response('404.html')

def calculate_age(born):
    today = date.today()
    try:
        birthday = born.replace(year=today.year)
    except ValueError:
        birthday = born.replace(year=today.year, day=born.day-1)
    if birthday > today:
        return today.year - born.year - 1
    else:
        return today.year - born.year

def handle_uploaded_file(f):
    with open('media/tmp/'+f.name, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

profiles/templates/edit.html
{% extends "base.html" %}

{% block title %}Edit your profile{% endblock title %}

{% block content %}
    {% if form %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit!" />
    </form>
    {% else %}
        form done.
    {% endif %}
{% endblock content %}

{% block js %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#id_birth_date").datepicker({
                dateFormat: "yy-mm-dd",
                display: "none"
            });
        })
    </script>
{% endblock js %}

profiles/templates/friends.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Friends of {{ request.username }}{% endblock title %}
{% block content %}
    <h1>Friends of <a href="{% url specific_url member.username %}">{{ member.first_name }}</a>'s</h1>
    {% for friend in friends.all %}
    <div class="friend">
        <div class="picture">
            {% thumbnail friend.get_profile.profile_pic "150x150" crop="center" as im %}
                <img src="{{ im.url }}" />
            {% endthumbnail %}
        </div>
        <div class="details">
            <div class="name">{{ friend.get_full_name }}</div>
            <div class="birthday">{{ friend.get_profile.birth_date|date:"Y.m.d" }}</div>
            <div class="country">{{ friend.get_profile.countries}}</div>
        </div>
    </div>
    {% endfor %}
{% endblock content %}

profiles/templates/login.html
{% extends "base.html" %}

{% block title %}{% endblock title %}

{% block content %}
Please log in above or <a href="{% url profiles.views.User_Profile_Registration %}">register here</a>
{% endblock content %}

profiles/templates/profile.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ profiles.first_name }}'s profile{% endblock title %}

{% block content %}
    {% if friendable == 0 %}
        <div class="add_friend"><a href="/profile/{{ profiles.username }}/add/">Add Friend</a></div>
    {% else %}
        {% if friendable != "none" %}
            <div class="chat_with_friend"><a href="/chat/{{ profiles.username }}">Chat</a></div>
            <div class="remove_friend"><a href="/profile/{{ profiles.username }}/remove/">Remove Friend</a></div>
        {% else %}
            <div class="edit_yourself"><a href="/edit/">Edit profile</a></div>
            <div class="friendlist"><a href="{% url friendlist profiles.username %}">Friends</a></div>
        {% endif %}
    {% endif %}
    <div class="user_profile">
        <div class="picture">
            {% thumbnail profiles.get_profile.profile_pic "150x150" crop="center" as im %}
                <img src="{{ im.url }}" />
            {% endthumbnail %}
        </div>
        <div class="details">
            <div class="name">{{ profiles.get_full_name }} <span class="smaller">({{ age }})</span></div>
            <div class="birthday">{{ profiles.get_profile.birth_date|date:"Y.m.d" }}</div>
            <div class="country">{{ profiles.get_profile.countries}}</div>
        </div>
    </div>
{% endblock content %}

profiles/templates/register.html
{% extends "base.html" %}

{% block title %}Register stuff{% endblock title %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register" />
    </form>
{% endblock content %}

{% block js %}
<script type="text/javascript">
    $().ready(function(){
        $("#id_birth_date").datepicker({
                                            dateFormat: "yy-mm-dd",
                                            changeMonth: true,
                                            changeYear: true,
                                            yearRange: "1900:"});
    })
</script>
{% endblock js %}

profiles/templates/registered.html
{% extends "base.html" %}

{% block title %}Registered{% endblock title %}

{% block content %}
    You can log in now! Use the login form above.
{% endblock content %}

profiles/templates/search.html
{% extends "base.html" %}
{% block title %}SEARCH{% endblock title %}
{% block content %}
    {% for search_result in search_results %}
        <a href="{% url specific_url search_result.username %}">{{ search_result.get_full_name }}</a>
    {% endfor %}
{% endblock content %}